# Generated by Django 2.2 on 2024-11-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0008_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-dt_created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-dt_created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dt_create',
            new_name='dt_created',
        ),
    ]
